import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { PlusCircle, Loader2, ArrowLeft, Send } from 'lucide-react';

export default function DispatchForm({ onCancel }) {
  const { token } = useAuth();
  const { addToast } = useToast();
  
  const [agents, setAgents] = useState([]);
  const [loadingAgents, setLoadingAgents] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // Form Fields
  const [orderId, setOrderId] = useState('');
  const [recipientName, setRecipientName] = useState('');
  const [deliveryAddress, setDeliveryAddress] = useState('');
  const [agentId, setAgentId] = useState('');
  const [scheduledDate, setScheduledDate] = useState('');
  const [notes, setNotes] = useState('');

  useEffect(() => {
    const fetchAgents = async () => {
      setLoadingAgents(true);
      try {
        const response = await fetch('/api/agents', {
          headers: { Authorization: `Bearer ${token}` }
        });
        const data = await response.json();
        if (!response.ok) throw new Error(data.error || 'Failed to load agents');
        setAgents(data.agents || []);
      } catch (error) {
        addToast(error.message, 'error');
      } finally {
        setLoadingAgents(false);
      }
    };
    fetchAgents();
  }, [token]);

  // Autogenerate unique Order ID for testing convenience
  const generateOrderId = () => {
    const rand = Math.floor(1000 + Math.random() * 9000);
    setOrderId(`ORD-${new Date().getFullYear()}-${rand}`);
    addToast('Order ID autogenerated!', 'info');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!orderId || !recipientName || !deliveryAddress || !agentId || !scheduledDate) {
      addToast('Please fill out all required fields.', 'error');
      return;
    }

    setSubmitting(true);
    try {
      const response = await fetch('/api/dispatches', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          order_id: orderId,
          recipient_name: recipientName,
          delivery_address: deliveryAddress,
          agent_id: parseInt(agentId),
          scheduled_date: scheduledDate,
          notes
        })
      });

      const data = await response.json();

      if (!response.ok) throw new Error(data.error || 'Failed to create dispatch');

      addToast('Dispatch created successfully!', 'success');
      // Clear form
      setOrderId('');
      setRecipientName('');
      setDeliveryAddress('');
      setAgentId('');
      setScheduledDate('');
      setNotes('');
      
      // Callback to return to dashboard
      if (onCancel) onCancel();
    } catch (error) {
      addToast(error.message, 'error');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="animate-fade-in max-w-2xl mx-auto py-4">
      {/* Title Header */}
      <div className="flex items-center gap-3 mb-6">
        <button 
          onClick={onCancel}
          className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200 border border-slate-200/40 dark:border-slate-800/40 bg-white/50 dark:bg-slate-900/50"
        >
          <ArrowLeft className="h-4 w-4" />
        </button>
        <div>
          <h2 className="text-2xl font-extrabold tracking-tight text-slate-850 dark:text-slate-100">Create New Dispatch</h2>
          <p className="text-xs text-slate-400">Register and assign a gift delivery record</p>
        </div>
      </div>

      {/* Form Card */}
      <form onSubmit={handleSubmit} className="glass-card border border-slate-200/60 dark:border-slate-800/60 p-6 rounded-2xl space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Order ID */}
          <div>
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">
              Order ID <span className="text-rose-500">*</span>
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                placeholder="e.g. ORD-2026-1025"
                value={orderId}
                onChange={(e) => setOrderId(e.target.value)}
                className="flex-1 px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all font-semibold"
                required
              />
              <button
                type="button"
                onClick={generateOrderId}
                className="px-3 py-2 text-xs font-bold bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 rounded-xl transition-all active:scale-95 border border-slate-200 dark:border-slate-700"
              >
                Auto-gen
              </button>
            </div>
          </div>

          {/* Scheduled Date */}
          <div>
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">
              Scheduled Date <span className="text-rose-500">*</span>
            </label>
            <input
              type="date"
              value={scheduledDate}
              onChange={(e) => setScheduledDate(e.target.value)}
              className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all"
              required
            />
          </div>

          {/* Recipient Name */}
          <div className="md:col-span-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">
              Recipient Name <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              placeholder="e.g. Alice Smith"
              value={recipientName}
              onChange={(e) => setRecipientName(e.target.value)}
              className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all"
              required
            />
          </div>

          {/* Delivery Address */}
          <div className="md:col-span-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">
              Delivery Address <span className="text-rose-500">*</span>
            </label>
            <textarea
              placeholder="e.g. Apartment 4B, 100 Broadway St, New York, NY 10005"
              value={deliveryAddress}
              onChange={(e) => setDeliveryAddress(e.target.value)}
              rows={3}
              className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all resize-none"
              required
            />
          </div>

          {/* Delivery Agent */}
          <div className="md:col-span-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">
              Assign Delivery Agent <span className="text-rose-500">*</span>
            </label>
            <select
              value={agentId}
              onChange={(e) => setAgentId(e.target.value)}
              disabled={loadingAgents}
              className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all disabled:opacity-50"
              required
            >
              <option value="">-- Choose Agent --</option>
              {agents.map((agent) => (
                <option key={agent.id} value={agent.id}>
                  {agent.name} ({agent.email})
                </option>
              ))}
            </select>
          </div>

          {/* Notes */}
          <div className="md:col-span-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">Notes</label>
            <textarea
              placeholder="e.g. Gate intercom code is #1024. Deliver after 4 PM."
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all resize-none"
            />
          </div>
        </div>

        {/* Action Button Row */}
        <div className="flex gap-4 justify-end pt-4 border-t border-slate-100 dark:border-slate-800">
          <button
            type="button"
            onClick={onCancel}
            className="px-5 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 text-sm font-bold text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-850 transition-all active:scale-95"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={submitting}
            className="flex items-center justify-center gap-2 bg-brand-500 hover:bg-brand-600 text-white font-bold text-sm px-6 py-2.5 rounded-xl transition-all hover:scale-105 active:scale-95 disabled:opacity-55 disabled:scale-100 shadow-md shadow-brand-500/10"
          >
            {submitting ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <>
                <PlusCircle className="h-4 w-4" />
                Schedule Dispatch
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
